language: python
python:
    - "3.6.5"

# setup environment
env:
- DJANGO_VERSION=2.1.2
- DJANGO_SETTINGS_MODULE='artwork_image_processor_site'

#before_install:
#  - export DJANGO_SETTINGS_MODULE=your_project.settings
#  - export PYTHONPATH=$HOME/builds/your_github_username/your_repo
  
#command to install
install:
#    - pip install .
    - pip install -r requirements.txt
#    - pip install Django==2.1.2
    
before_script: cd project  

#command to run tests
script:
#    - python manage.py makemigrations
#    - python manage.py migrate
    - python manage.py test
    
notifications:
    emails:
        recipients:
            - wunyanw@gmail.com
        on_success: never
        on_failure: always
